<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RailroadTycoon3SaveManager</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="FluentIcons.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\SaveGameControl.axaml.cs">
      <DependentUpon>SaveGameControl.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
